service: lambda-http-proxy

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  timeout: 10 #Default Lambda timeout 
  memorySize: 512 #Default Lambda Memory Size
  versionFunctions: true # No functions versioning 
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**
      - .test/**

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 5

  serverless-offline:
    host: '0.0.0.0'

plugins:
  - serverless-offline
  - serverless-prune-plugin

functions:
  proxy:
    handler: handler.proxy
    events:
      - http:
          path: /{proxy+}
          method: any
